### ISSUE TITLE
Primary Key Cluster not understood

### ISSUE THREAD

**Issue by sureshbabuchitturi** [dalibo/sqlserver2pgsql#98] opened 2019-03-15 12:09 UTC
hi while running script i am getting error

Primary Key Cluster not understood

sample create statement for tables all are the same sql server 2016
```
CREATE TABLE [etl].[account_handle](
	[acct_event_id] [bigint] NOT NULL,
	[acct_id] [bigint] NOT NULL,
	[comment_id] [bigint] NULL,
	[descrip] [varchar](500) NULL,
	[event_cat_id] [bigint] NOT NULL,
	[event_date] [datetime] NOT NULL,
	[event_end_time] [varchar](20) NULL,
	[event_start_time] [varchar](20) NULL,
	[event_type_id] [bigint] NOT NULL,
	[problem_cd] [bigint] NULL,
	[reason_cd] [bigint] NULL,
	[resolution] [varchar](2048) NULL,
	[user_id] [bigint] NULL,
	[ext_user_name] [varchar](100) NULL,
	[level1_id] [bigint] NULL,
	[level2_id] [bigint] NULL,
	[level3_id] [bigint] NULL,
	[level4_id] [bigint] NULL,
	[group_id] [bigint] NULL,
	[escalation_id] [bigint] NULL,
	[level5_id] [bigint] NULL,
	[reference_id] [bigint] NULL,
	[entity] [varchar](50) NULL,
	[modified_ts] [datetime] NOT NULL,
	[device_type_id] [bigint] NULL,
	[device_error_codes] [varchar](1024) NULL,
PRIMARY KEY CLUSTERED 
(
	[acct_event_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
```

**Comment by madtibo** [comment] 2019-03-20 13:03
hello @sureshbabuchitturi 
Thank you for the information.
There is indeed a problem caused by the absence of a named constraint for the primary key.
The problem should be solved in last commit. Could you try and tell me if you experience any problem?

**Comment by madtibo** [comment] 2019-04-02 08:01
It should be solved.
I close the issue.

**Closed by madtibo** 2019-04-02 08:01 UTC
