### ISSUE TITLE
add option to skip errors

### ISSUE THREAD

**Issue by mfriedemann** [dalibo/sqlserver2pgsql#60] opened 2017-03-09 15:29 UTC
Hey,

after massaging the MSSQL dump to work around the other small issues, the migration of a complex DB fails without mentioning any specific cause:
```
Table output.6 - ERROR (version 5.4.0.1-130, build 1 from 2015-06-14_12-34-55 by buildguy) : Unexpected batch update error committing the database connection.
Table output.6 - ERROR (version 5.4.0.1-130, build 1 from 2015-06-14_12-34-55 by buildguy) : org.pentaho.di.core.exception.KettleDatabaseBatchException: 
Table output.6 - Error updating batch
Table output.6 - Batch entry 2 INSERT INTO "public"."-redacted-" ("ID", "Name", "-redacted") VALUES ( '-redacted-',  NULL,  NULL) was aborted.  Call getNextException to see the cause.
Table output.6 - 
Table output.6 - 	at org.pentaho.di.core.database.Database.createKettleDatabaseBatchException(Database.java:1386)
Table output.6 - 	at org.pentaho.di.core.database.Database.emptyAndCommit(Database.java:1375)
Table output.6 - 	at org.pentaho.di.trans.steps.tableoutput.TableOutput.dispose(TableOutput.java:575)
Table output.6 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:96)
Table output.6 - 	at java.lang.Thread.run(Thread.java:745)
Table output.6 - Caused by: java.sql.BatchUpdateException: Batch entry 2 INSERT INTO "public"."-redacted-" ("ID", "Name", "-redacted-") VALUES ( '-redacted-',  NULL,  NULL) was aborted.  Call getNextException to see the cause.
Table output.6 - 	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
Table output.6 - 	at org.postgresql.core.v3.QueryExecutorImpl$1.handleError(QueryExecutorImpl.java:461)
Table output.6 - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
Table output.6 - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
Table output.6 - 	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
Table output.6 - 	at org.pentaho.di.core.database.Database.emptyAndCommit(Database.java:1362)
Table output.6 - 	... 3 more
[dbo].[-redacted-] - ERROR (version 5.4.0.1-130, build 1 from 2015-06-14_12-34-55 by buildguy) : Errors detected!
[dbo].[-redacted-] - ERROR (version 5.4.0.1-130, build 1 from 2015-06-14_12-34-55 by buildguy) : Errors detected!
Kitchen - ERROR (version 5.4.0.1-130, build 1 from 2015-06-14_12-34-55 by buildguy) : Finished with errors
```

The trouble, apart from not specifiying any actual cause, is that it bails out completely.

It would be nice if the behaviour could be configurable, so that the errors could be logged, but processing of other rows and other tables could continue unaffected.

If my limited research is correct, the kettle job/transformation can be set up with a general and/or specific handler for such errors, but a quick attempty at adding one to the <step_error_handling> element did not work.

**Comment by marco44** [comment] 2017-03-09 20:53
Hi,

For the cause, yes, sometimes the error from kettle is not very easy to see. The easiest way is to go to postgresql's log file. There, the error is usually very clearly stated.

For the possibility to skip errors, I'll try to work on something, but it will take some time (busy schedule for the next few days).

**Comment by marco44** [comment] 2017-06-12 13:41
Sorry, it was even busier than I thought. Committed 988e26e for this. I don't really have an environment to test it. If you still have one, please test.

**Comment by gfauvie** [comment] 2017-06-17 18:31
Hi,
It looks there is a bug (or maybe a wrong way to use this script):

[root@proliant sqlserver2pgsql]# ./sqlserver2pgsql.pl -f /home/stranix/avocats-liege-data-simple.sql -b /home/stranix/before.sql -a /home/stranix/after.sql -u /home/stranix/unsecure.sql -ignore_errors
Line <INSERT [dbo].[a_temp_pk_int] ([pk_int]) VALUES (28000)
> (3797) not understood. This is a bug at ./sqlserver2pgsql.pl line 2198, <$file> line 3797.

Any idea ?

Kind Regards,

**Comment by marco44** [comment] 2017-06-18 10:41
Please create a new thread, as this is a new issue

**Closed** 2017-09-11 06:40 UTC
