### ISSUE TITLE
Column names "Time" and "Name" kettle converts to "time" and "name" - ERROR

### ISSUE THREAD

**Issue by cowabunga1** [dalibo/sqlserver2pgsql#22] opened 2015-04-27 12:34 UTC
./sqlserver2pgsql.pl -i -b ./out/before.sql -a out/after.sql -u out/unsure.sql -keep_identifier_case -k out/kettledir \ -sd source -sh 192.168.0.127 -sp 1433 -sd nkr -si SQL -su sa -sw sa \ -pd dest -ph 192.168.0.127 -pp 5432 -pd nkr -pu postgres -pw postgres -f ./in/nkr-generate.sql

before and after scripts generates flawlessly

What problem on doing migrate with kitchen.sh?

2015/04/27 15:29:34 - Table input.0 - Finished processing (I=657, O=0, R=0, W=657, U=0, E=0)
2015/04/27 15:29:34 - Table output.2 - ERROR (version 5.3.0.0-213, build 1 from 2015-02-02_12-17-08 by buildguy) : Unexpected batch update error committing the database connection.
2015/04/27 15:29:34 - Table output.7 - ERROR (version 5.3.0.0-213, build 1 from 2015-02-02_12-17-08 by buildguy) : Unexpected batch update error committing the database connection.
2015/04/27 15:29:34 - Table output.2 - ERROR (version 5.3.0.0-213, build 1 from 2015-02-02_12-17-08 by buildguy) : org.pentaho.di.core.exception.KettleDatabaseBatchException: 
2015/04/27 15:29:34 - Table output.2 - Error updating batch
2015/04/27 15:29:34 - Table output.2 - Batch entry 0 INSERT INTO "public"."ExtCompositions" ("Mask", "mask_change_owner", "CompositionId", "ParentId", "Node", "time", "name", "Shifr", "Marka", "Volume", "Plast", "Del", "id") VALUES ( 4,  4,  641378322,  0,  0,  '2015-04-07 10:04:26.000000 +03:00:00',  '6004-004',  '00000000002',  '00-00000202',  100,  0,  0,  3) was aborted.  Call getNextException to see the cause.
2015/04/27 15:29:34 - Table output.2 - 
2015/04/27 15:29:34 - Table output.2 - 	at org.pentaho.di.core.database.Database.createKettleDatabaseBatchException(Database.java:1351)
2015/04/27 15:29:34 - Table output.2 - 	at org.pentaho.di.core.database.Database.emptyAndCommit(Database.java:1340)
2015/04/27 15:29:34 - Table output.2 - 	at org.pentaho.di.trans.steps.tableoutput.TableOutput.dispose(TableOutput.java:571)
2015/04/27 15:29:34 - Table output.2 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:96)
2015/04/27 15:29:34 - Table output.2 - 	at java.lang.Thread.run(Thread.java:745)
2015/04/27 15:29:34 - Table output.2 - Caused by: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO "public"."ExtCompositions" ("Mask", "mask_change_owner", "CompositionId", "ParentId", "Node", "time", "name", "Shifr", "Marka", "Volume", "Plast", "Del", "id") VALUES ( 4,  4,  641378322,  0,  0,  '2015-04-07 10:04:26.000000 +03:00:00',  '6004-004',  '00000000002',  '00-00000202',  100,  0,  0,  3) was aborted.  Call getNextException to see the cause.

**Comment by marco44** [comment] 2015-04-27 14:14
Hi, I don't have any clue here, as I don't see the error (probably not a high enough debug level in kettle). Can you give a look at PostgreSQL's log, you should have the SQL error as plain text in it ?

**Comment by marco44** [comment] 2015-04-28 08:03
After giving it a second look (and reading the title, I must have been tired yesterday), yeah, the problem is that kettle destroys the case of those columns :)

I will look into it, but it looks like a kettle bug

**Comment by marco44** [comment] 2015-04-28 09:16
Support for not messing up case of words which also are identifiers seems to have been added recently to PDI. I added support for that to sqlserver2pgsql in the 7e996663b17952caa03f5e1598beb410c32089bd commit. I hope it solves the issue. Please test and tell me. It seems to work here with PDI 5.3.0

**Comment by marco44** [comment] 2015-07-10 11:06
Any news on this ? If not, I'll close this issue in a few days.

Regards

**Closed** 2015-08-10 13:11 UTC
