### ISSUE TITLE
Can't migrate date field

### ISSUE THREAD

**Issue by fedotxxl** [dalibo/sqlserver2pgsql#72] opened 2017-09-15 15:47 UTC
Hello
I got an exception when I try to execute: `./kitchen.sh`:

```
2017/09/15 18:45:42 - SQL SCRIPT START - Couldn't execute SQL: CREATE CAST (varchar as date) with inout as implicit
2017/09/15 18:45:42 - SQL SCRIPT START - 
2017/09/15 18:45:42 - SQL SCRIPT START - ERROR: must be owner of type character varying or type date

```

I created this cast manually with user `postgres` and removed line `CREATE CAST &#x28;varchar as date&#x29; with inout as implicit;`

Now I can't migrate my data:

```
2017/09/15 18:47:30 - Table output.0 - Error inserting row into table ["databasechangeloglock"] with values: [1], [N], [null], [null]
2017/09/15 18:47:30 - Table output.0 - 
2017/09/15 18:47:30 - Table output.0 - Error inserting/updating row
2017/09/15 18:47:30 - Table output.0 - ERROR: column "lockgranted" is of type timestamp without time zone but expression is of type character varying
2017/09/15 18:47:30 - Table output.0 -   Hint: You will need to rewrite or cast the expression.
2017/09/15 18:47:30 - Table output.0 -   Position: 109
2017/09/15 18:47:30 - Table output.0 - 
2017/09/15 18:47:30 - Table output.0 - 
2017/09/15 18:47:30 - Table output.0 -  at org.pentaho.di.trans.steps.tableoutput.TableOutput.writeToTable(TableOutput.java:385)
2017/09/15 18:47:30 - Table output.0 -  at org.pentaho.di.trans.steps.tableoutput.TableOutput.processRow(TableOutput.java:125)
2017/09/15 18:47:30 - Table output.0 -  at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2017/09/15 18:47:30 - Table output.0 -  at java.lang.Thread.run(Thread.java:745)
2017/09/15 18:47:30 - Table output.0 - Caused by: org.pentaho.di.core.exception.KettleDatabaseException: 
2017/09/15 18:47:30 - Table output.0 - Error inserting/updating row
2017/09/15 18:47:30 - Table output.0 - ERROR: column "lockgranted" is of type timestamp without time zone but expression is of type character varying
2017/09/15 18:47:30 - Table output.0 -   Hint: You will need to rewrite or cast the expression.
2017/09/15 18:47:30 - Table output.0 -   Position: 109
2017/09/15 18:47:30 - Table output.0 - 
2017/09/15 18:47:30 - Table output.0 -  at org.pentaho.di.core.database.Database.insertRow(Database.java:1321)
2017/09/15 18:47:30 - Table output.0 -  at org.pentaho.di.trans.steps.tableoutput.TableOutput.writeToTable(TableOutput.java:262)
2017/09/15 18:47:30 - Table output.0 -  ... 3 more
2017/09/15 18:47:30 - Table output.0 - Caused by: org.postgresql.util.PSQLException: ERROR: column "lockgranted" is of type timestamp without time zone but expression is of type character varying
2017/09/15 18:47:30 - Table output.0 -   Hint: You will need to rewrite or cast the expression.
2017/09/15 18:47:30 - Table output.0 -   Position: 109
```

It also doesn't work for non null dates

**Comment by fedotxxl** [comment] 2017-09-15 17:04
I've added 

`<attribute><code>EXTRA_OPTION_POSTGRESQL.stringtype</code><attribute>unspecified</attribute></attribute>`

to every `ktr` file and fixed the problem

**Comment by tfredy2** [comment] 2017-10-03 16:38
Hello, @fedotxxl you added to one for one or modified the migration tool?
I've the same problem, but the database has 2500 tables.
thanks in advance

**Comment by tfredy2** [comment] 2017-10-03 18:27
@fedotxxl apparently a solution most easy is modify tool in me case had problem with the data type datemite2 at migrate a timestamp without timezone, changue the value to timestamp with timezone. 
Well to me worked
for example:

# There is still a special case for text types and case insensitivity (see convert_type) though
my %types = ('int'              => 'int',
             'nvarchar'         => 'varchar',
             'nchar'            => 'char',
             'char'             => 'char',
             'varchar'          => 'varchar',
             'text'             => 'text',
             'char'             => 'char',
             'smallint'         => 'smallint',
             'tinyint'          => 'smallint',
             'bigint'           => 'bigint',
             'decimal'          => 'numeric',
             'float'            => 'double precision',
             'real'             => 'real',
             'date'             => 'date',
             'datetime'         => 'timestamp',
             'datetime2'        => 'timestamp',
             'smalldatetime'    => 'timestamp',
             'time'             => 'time',
             'timestamp'        => 'bytea',
             'rowversion'        => 'bytea',
             'datetimeoffset'   => 'timestamp with time zone',
             'image'            => 'bytea',
             'binary'           => 'bytea',
             'varbinary'        => 'bytea',
             'money'            => 'numeric',
             'smallmoney'       => 'numeric(6,4)',
             'uniqueidentifier' => 'uuid',
             'xml'              => 'xml',);


I Changue this 

# There is still a special case for text types and case insensitivity (see convert_type) though
my %types = ('int'              => 'int',
             'nvarchar'         => 'varchar',
             'nchar'            => 'char',
             'char'             => 'char',
             'varchar'          => 'varchar',
             'text'             => 'text',
             'char'             => 'char',
             'smallint'         => 'smallint',
             'tinyint'          => 'smallint',
             'bigint'           => 'bigint',
             'decimal'          => 'numeric',
             'float'            => 'double precision',
             'real'             => 'real',
             'date'             => 'date',
             'datetime'         => 'timestamp',
             **'datetime2'        => 'timestamp with time zone',**
             'smalldatetime'    => 'timestamp',
             'time'             => 'time',
             'timestamp'        => 'bytea',
             'rowversion'        => 'bytea',
             'datetimeoffset'   => 'timestamp with time zone',
             'image'            => 'bytea',
             'binary'           => 'bytea',
             'varbinary'        => 'bytea',
             'money'            => 'numeric',
             'smallmoney'       => 'numeric(6,4)',
             'uniqueidentifier' => 'uuid',
             'xml'              => 'xml',);

I hope it works

**Comment by madtibo** [comment] 2018-06-20 10:06
@beaud76 is looking into this
This seems to be linked to #35, #65 and #37 
We will check whether this option can / should be included systematically into the ktr files.

we have a link [here](https://jdbc.postgresql.org/documentation/83/connect.html) about the `EXTRA_OPTION_POSTGRESQL.stringtype=unspecified` option

**Comment by jediwarpraptor** [comment] 2018-07-21 15:37
Definitely need to have the option to include `stringtype=unspecified` as a sensible default.  I just had to do bulk edits of 200 `.ktr` files in order to get the migration to work for the MSSQL (`Datetime` / `Datetime2`) to PGSQL(`timestamp`) fields

**Comment by madtibo** [comment] 2018-07-23 09:57
Since we are not sure about this option impact, we will add a new option.

**Comment by madtibo** [comment] 2018-10-05 13:29
@fedotxxl @tfredy2 @jediwarpraptor 
Could you check if your problem is solved using the "-stringtype_unspecified" on #95 ?

**Comment by madtibo** [comment] 2019-03-20 11:06
branch merged

**Closed by madtibo** 2019-03-20 11:06 UTC
Labels: enhancement, fixed

**Comment by jpmeijers** [comment] 2021-01-19 08:44
```
2021/01/19 08:28:34 - Table output.0 - Batch entry 0 INSERT INTO ... (... "starttime", "endtime" ...) VALUES (...  '00:00:00.0',  '01:00:00.0' ...), was aborted: ERROR: column "starttime" is of type time without time zone but expression is of type character varying
2021/01/19 08:28:34 - Table output.0 -   Hint: You will need to rewrite or cast the expression.
```

I experienced this same issue, and I can confirm that adding `-stringtype_unspecified` solved the error.
